import DWorkbench
import AVFAudio
import SwiftUI

/// System speech is explicit and independent of the selected generation model.
struct ChatSpeechPanel: View {
    let chat: ChatController
    let project: ProjectSession
    let sessionID: UUID
    let onImportAudio: (String) -> Void
    var onOpenSettings: (() -> Void)? = nil
    @Environment(\.dLanguageStore) private var language
    @State private var recognitionLanguage: ChatSpeechRecognitionLanguage?
    @State private var capability: ChatSpeechCapability?
    @State private var issue: String?
    private func text(_ en: String, _ zh: String) -> String { language?.effectiveLanguageIdentifier.hasPrefix("zh") == true ? zh : en }
    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(text("Voice input", "语音输入")).font(.headline)
            VStack(alignment: .leading, spacing: 8) {
                Text(text("On-device transcription only. The original recording is kept. Review the transcript before sending; it is not generated by your selected chat model.", "仅使用本机转写，保留原录音。转写先供您审核，不自动发送；朗读使用系统声音，与所选聊天模型无关。"))
                    .font(.caption).foregroundStyle(.secondary)
                Picker(text("Recognition language", "识别语言"), selection: $recognitionLanguage) {
                    Text(text("Choose a language", "选择语言"))
                        .tag(nil as ChatSpeechRecognitionLanguage?)
                    Text(text("Mandarin Chinese (zh-CN)", "普通话（zh-CN）"))
                        .tag(Optional(ChatSpeechRecognitionLanguage.mandarin))
                    Text(text("English (en-US)", "英语（en-US）"))
                        .tag(Optional(ChatSpeechRecognitionLanguage.english))
                }
                    .disabled(chat.isTranscribing || project.chatRecordingSessionID != nil)
                    .accessibilityIdentifier("chat-recognition-language")
                    .onChange(of: recognitionLanguage) { _, value in
                        capability = value.map { chat.speech.capability(localeIdentifier: $0.rawValue) }
                    }
                if let recognitionLanguage, let capability {
                    Text(text("Selected: \(recognitionLanguage.rawValue)", "已选择：\(recognitionLanguage.rawValue)"))
                        .font(.caption)
                    Text(text("Speech permission: \(authorizationText(capability.authorization))",
                              "语音识别权限：\(authorizationText(capability.authorization))"))
                        .font(.caption).foregroundStyle(.secondary)
                    Text(capability.supportsOnDeviceRecognition
                         ? text("Offline resources: unconfirmed until transcription; on-device recognition is supported.",
                                "离线资源：转写前尚未确认；系统支持本机识别。")
                         : text("Offline resources: unavailable for this language.",
                                "离线资源：此语言不可用。"))
                        .font(.caption).foregroundStyle(.secondary)
                    Text(capability.recognizerAvailable
                         ? text("Recognizer: currently available.", "识别器：当前可用。")
                         : text("Recognizer: currently unavailable.", "识别器：当前不可用。"))
                        .font(.caption).foregroundStyle(.secondary)
                } else {
                    Text(text("Choose a language before transcribing or recording.", "请先选择语言，再转写或录音。"))
                        .font(.caption).foregroundStyle(.secondary)
                }
                if capability?.authorization == .notDetermined, capability?.localeIdentifier != nil {
                    Button(text("Authorize local transcription…", "允许本地转写…")) {
                        Task {
                            _ = await chat.speech.requestRecognitionAuthorization()
                            capability = recognitionLanguage.map {
                                chat.speech.capability(localeIdentifier: $0.rawValue)
                            }
                        }
                    }
                }
                HStack {
                    Button(text("Choose audio and transcribe…", "选择音频并转写…")) {
                        if let recognitionLanguage { onImportAudio(recognitionLanguage.rawValue) }
                    }
                        .disabled(project.isBusy || capability?.canTranscribeLocally != true)
                        .accessibilityIdentifier("chat-transcribe-file")
                    if project.chatRecordingSessionID != nil {
                        Button(text("Finish recording", "结束录音")) { Task { await project.finishChatRecording() } }
                            .buttonStyle(.borderedProminent)
                    } else {
                        Button(text("Record voice", "录制语音")) {
                            if let recognitionLanguage {
                                Task { await project.startChatRecording(sessionID: sessionID, controller: chat,
                                                                        locale: recognitionLanguage.rawValue) }
                            }
                        }.disabled(project.isBusy || capability?.canTranscribeLocally != true)
                    }
                    if chat.isTranscribing {
                        Button(text("Stop transcription", "停止转写")) { Task { await chat.cancelSpeechTranscription() } }
                        Text(String(describing: chat.speechRecognitionState)).font(.caption)
                    }
                }
                if let draft = chat.speechDrafts[sessionID] {
                    Text(draft.textSnapshot ?? "").textSelection(.enabled)
                    HStack {
                        Button(text("Append to draft", "加入待发送草稿")) { change { try chat.adoptSpeechDraft(sessionID: sessionID) } }
                        Button(text("Dismiss transcript", "不采用转写")) { change { try chat.discardSpeechDraft(sessionID: sessionID) } }
                    }
                }
                Divider()
                Button(text("Voice and speed settings…", "朗读声音与语速设置…")) { onOpenSettings?() }
                    .disabled(onOpenSettings == nil)
                HStack {
                    Button(text("Read draft", "朗读草稿")) {
                        change { try chat.speech.speak(chat.state.sessions.first { $0.id == sessionID }?.draft ?? "") }
                    }.disabled(chat.speechPlaybackState != .idle)
                    if chat.speechPlaybackState == .speaking { Button(text("Pause", "暂停")) { chat.speech.pauseSpeech() } }
                    if chat.speechPlaybackState == .paused { Button(text("Resume", "继续")) { chat.speech.resumeSpeech() } }
                    if chat.speechPlaybackState != .idle { Button(text("Stop reading", "停止朗读")) { chat.speech.stopSpeech() } }
                }
                if let issue { Text(ChatErrorText.display(issue, language: language)).foregroundStyle(.red).textSelection(.enabled) }
                if let message = project.errorMessage { Text(message).foregroundStyle(.red).font(.caption) }
            }
        }.task {
            if let recognitionLanguage {
                capability = chat.speech.capability(localeIdentifier: recognitionLanguage.rawValue)
            }
        }
    }
    private func authorizationText(_ authorization: ChatSpeechAuthorization) -> String {
        switch authorization {
        case .notDetermined: text("not requested", "未请求")
        case .denied: text("denied", "已拒绝")
        case .restricted: text("restricted", "受限制")
        case .authorized: text("allowed", "已允许")
        }
    }
    private func change(_ action: () throws -> Void) {
        do { try action(); issue = nil } catch { issue = error.localizedDescription }
    }
}
