import DWorkbench
import SwiftUI

/// System speech is explicit and independent of the selected generation model.
struct ChatSpeechPanel: View {
    let chat: ChatController
    let project: ProjectSession
    let sessionID: UUID
    let onImportAudio: (String) -> Void
    @Environment(\.dLanguageStore) private var language
    @State private var locale = Locale.current.identifier.replacingOccurrences(of: "_", with: "-")
    @State private var voice = ""
    @State private var rate: Double = 0.5
    @State private var capability: ChatSpeechCapability?
    @State private var issue: String?
    private func text(_ en: String, _ zh: String) -> String { language?.effectiveLanguageIdentifier.hasPrefix("zh") == true ? zh : en }
    var body: some View {
        DisclosureGroup(text("Voice input and system read-aloud", "语音输入与系统朗读")) {
            VStack(alignment: .leading, spacing: 8) {
                Text(text("On-device transcription only. The original recording is kept. Review the transcript before sending; it is not generated by your selected chat model.", "仅使用本机转写，保留原录音。转写先供您审核，不自动发送；朗读使用系统声音，与所选聊天模型无关。"))
                    .font(.caption).foregroundStyle(.secondary)
                TextField(text("Recognition language (BCP-47)", "识别语言（如 zh-CN / en-US）"), text: $locale)
                    .disabled(chat.isTranscribing || project.chatRecordingSessionID != nil)
                    .onChange(of: locale) { _, value in capability = chat.speech.capability(localeIdentifier: value) }
                if capability?.authorization != .authorized {
                    Button(text("Authorize local transcription…", "允许本地转写…")) {
                        Task { _ = await chat.speech.requestRecognitionAuthorization(); capability = chat.speech.capability(localeIdentifier: locale) }
                    }
                }
                if capability?.supportsOnDeviceRecognition == false {
                    Text(text("The system does not currently provide offline recognition for this language. No cloud fallback will be used.", "系统当前没有提供该语言的离线识别；不会转向云端。"))
                        .font(.caption).foregroundStyle(.secondary)
                }
                HStack {
                    Button(text("Choose audio and transcribe…", "选择音频并转写…")) { onImportAudio(locale) }
                        .disabled(project.isBusy || capability?.canTranscribeLocally != true)
                        .accessibilityIdentifier("chat-transcribe-file")
                    if project.chatRecordingSessionID != nil {
                        Button(text("Finish recording", "结束录音")) { Task { await project.finishChatRecording() } }
                            .buttonStyle(.borderedProminent)
                    } else {
                        Button(text("Record voice", "录制语音")) {
                            Task { await project.startChatRecording(sessionID: sessionID, controller: chat, locale: locale) }
                        }.disabled(project.isBusy || capability?.canTranscribeLocally != true)
                    }
                    if chat.isTranscribing {
                        Button(text("Stop transcription", "停止转写")) { Task { await chat.cancelSpeechTranscription() } }
                        Text(String(describing: chat.speechRecognitionState)).font(.caption)
                    }
                }
                if let draft = chat.speechDrafts[sessionID] {
                    Text(draft.textSnapshot ?? "").textSelection(.enabled)
                    HStack {
                        Button(text("Append to draft", "加入待发送草稿")) { change { try chat.adoptSpeechDraft(sessionID: sessionID) } }
                        Button(text("Dismiss transcript", "不采用转写")) { change { try chat.discardSpeechDraft(sessionID: sessionID) } }
                    }
                }
                Divider()
                Picker(text("System voice", "系统声音"), selection: $voice) {
                    Text(text("System default", "系统默认")).tag("")
                    ForEach(chat.speech.availableVoices) { voice in Text(voice.name + " · " + voice.language).tag(voice.id) }
                }.onChange(of: voice) { _, value in
                    change { if value.isEmpty { try chat.speech.selectLanguage(locale) } else { try chat.speech.selectVoice(id: value) } }
                }
                HStack {
                    Text(text("Reading speed", "朗读速度"))
                    Slider(value: $rate, in: Double(chat.speech.rateRange.lowerBound)...Double(chat.speech.rateRange.upperBound))
                        .onChange(of: rate) { _, value in change { try chat.speech.setRate(Float(value)) } }
                }
                HStack {
                    Button(text("Read draft", "朗读草稿")) {
                        change { try chat.speech.speak(chat.state.sessions.first { $0.id == sessionID }?.draft ?? "") }
                    }.disabled(chat.speechPlaybackState != .idle)
                    if chat.speechPlaybackState == .speaking { Button(text("Pause", "暂停")) { chat.speech.pauseSpeech() } }
                    if chat.speechPlaybackState == .paused { Button(text("Resume", "继续")) { chat.speech.resumeSpeech() } }
                    if chat.speechPlaybackState != .idle { Button(text("Stop reading", "停止朗读")) { chat.speech.stopSpeech() } }
                }
                if let issue { Text(ChatErrorText.display(issue, language: language)).foregroundStyle(.red).textSelection(.enabled) }
                if let message = project.errorMessage { Text(message).foregroundStyle(.red).font(.caption) }
            }
        }.task { capability = chat.speech.capability(localeIdentifier: locale); rate = Double(chat.speech.rate); voice = chat.speech.voiceID ?? "" }
    }
    private func change(_ action: () throws -> Void) {
        do { try action(); issue = nil } catch { issue = error.localizedDescription }
    }
}
